<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Root</name>
   <tag></tag>
   <elementGuidId>e4705719-9f87-4bea-b2dd-839de994ee3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div#root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1546898199373</value>
   </webElementProperties>
</WebElementEntity>
